// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Staging.Infrastructure;

#nullable disable

namespace Staging.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20251229153403_FixHouseholdIdOnDataFlag")]
    partial class FixHouseholdIdOnDataFlag
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("staging")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Staging.Domain.AggregatesModel.ExternalSubmissionAggregate.ExternalSubmissionAggregate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("SourceId")
                        .HasColumnType("int");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("ExternalSubmission", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.Form", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FormStatusId")
                        .HasColumnType("int");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Help")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.HasKey("Id");

                    b.HasIndex("ShortName")
                        .IsUnique();

                    b.ToTable("Form", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExtendableTypeName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Help")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.HasIndex("ShortName");

                    b.ToTable("FormCategory", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormElement", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("AttributeKey")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Category")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CustomAttributeConfigurationGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("CustomAttributeTypeId")
                        .HasColumnType("int");

                    b.Property<int>("ElementTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FormCategoryId")
                        .HasColumnType("int");

                    b.Property<string>("FriendlyName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("FutureDateOnly")
                        .HasColumnType("bit");

                    b.Property<string>("Help")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsFormula")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("MultipleSelection")
                        .HasColumnType("bit");

                    b.Property<int?>("NumericMaxValue")
                        .HasColumnType("int");

                    b.Property<int?>("NumericMinValue")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<bool>("PastDateOnly")
                        .HasColumnType("bit");

                    b.Property<string>("RegEx")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("ShortName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("StringMaxLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormCategoryId");

                    b.HasIndex("ShortName");

                    b.ToTable("FormElement", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormElementAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AttributeTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FormElementId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FormElementId");

                    b.ToTable("FormElementAttribute", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormElementDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ComparisonFormElementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ComparisonValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DependencyRelationshipTypeId")
                        .HasColumnType("int");

                    b.Property<int>("FormElementId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("OperatorTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FormElementId");

                    b.ToTable("FormElementDependency", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FormId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("FormId");

                    b.ToTable("FormVersion", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.Package", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("FormId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PackageTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ParentOrgunitName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("System")
                        .HasColumnType("bit");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("UniqueCode")
                        .IsUnique();

                    b.ToTable("Package", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DataAcceptanceStageClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataManagementStageClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("GatewayStageClosed")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("LastTemporaryHouseholdId")
                        .HasColumnType("int");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OrgUnitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PackageId")
                        .HasColumnType("int");

                    b.Property<int>("PackageStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("PackageSubStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("StagePreparationClosed")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageEvent", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("DataFlagSubTypeId")
                        .HasColumnType("int");

                    b.Property<int>("DataFlagTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(750)
                        .HasColumnType("nvarchar(750)");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("IssueDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PackageEventHouseholdId")
                        .HasColumnType("int");

                    b.Property<int?>("PackageEventId")
                        .HasColumnType("int");

                    b.Property<int>("PriorityId")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("SystemGenerated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventId");

                    b.ToTable("PackageEventDataFlag", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlagComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OriginatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PackageEventDataFlagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventDataFlagId");

                    b.ToTable("PackageEventDataFlagComment", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EnumeratorName")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PackageEventId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventId");

                    b.ToTable("PackageEventDevice", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CollectionStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("CollectionStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("CommunityClassification")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HouseholdGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseholdHead")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("HouseholdId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ListingStatusDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ListingStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("PackageEventId")
                        .HasColumnType("int");

                    b.Property<string>("PhysicalAddress")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("VillageName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventId");

                    b.ToTable("PackageEventHousehold", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PackageEventHouseholdId")
                        .HasColumnType("int");

                    b.Property<bool>("ValueModified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdId");

                    b.ToTable("PackageEventHouseholdAttribute", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("HouseholdMemberGuid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("HouseholdMemberId")
                        .HasColumnType("int");

                    b.Property<string>("IDDocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PackageEventHouseholdId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdId");

                    b.ToTable("PackageEventHouseholdMember", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMemberAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PackageEventHouseholdMemberId")
                        .HasColumnType("int");

                    b.Property<bool>("ValueModified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdMemberId");

                    b.ToTable("PackageEventHouseholdMemberAttribute", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("FailureMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("PackageEventHouseholdId")
                        .HasColumnType("int");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("PayloadProcessedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PayloadProcessedId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("PayloadStatusDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdId");

                    b.ToTable("PackageEventHouseholdSynch", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynchMetaAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MetaAttributeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("MetaAttributeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PackageEventHouseholdSynchId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdSynchId");

                    b.ToTable("PackageEventHouseholdSynchMetaAttribute", "staging");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.ExternalSubmissionAggregate.ExternalSubmissionAggregate", b =>
                {
                    b.OwnsMany("Staging.Domain.AggregatesModel.ExternalSubmissionAggregate.ExternalSubmission", "Submissions", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("AttemptCount")
                                .HasColumnType("int");

                            b1.Property<DateTime>("CreatedAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("ExternalId")
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<int>("ExternalSubmissionId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("LastAttemptAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Message")
                                .HasMaxLength(500)
                                .HasColumnType("nvarchar(500)");

                            b1.Property<string>("Payload")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Status")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("Vendor")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("ExternalSubmissionId");

                            b1.ToTable("ExternalSubmissionItems", "staging");

                            b1.WithOwner()
                                .HasForeignKey("ExternalSubmissionId");
                        });

                    b.Navigation("Submissions");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.Form", b =>
                {
                    b.OwnsOne("Staging.Domain.AggregatesModel.FormAggregate.Version", "CurrentVersion", b1 =>
                        {
                            b1.Property<int>("FormId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.HasKey("FormId");

                            b1.ToTable("Form", "staging");

                            b1.WithOwner()
                                .HasForeignKey("FormId");
                        });

                    b.Navigation("CurrentVersion");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormCategory", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.FormAggregate.Form", null)
                        .WithMany("Categories")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Staging.Domain.AggregatesModel.FormAggregate.Version", "VersionCreated", b1 =>
                        {
                            b1.Property<int>("FormCategoryId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.HasKey("FormCategoryId");

                            b1.ToTable("FormCategory", "staging");

                            b1.WithOwner()
                                .HasForeignKey("FormCategoryId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.FormAggregate.Version", "VersionDeleted", b1 =>
                        {
                            b1.Property<int>("FormCategoryId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.HasKey("FormCategoryId");

                            b1.ToTable("FormCategory", "staging");

                            b1.WithOwner()
                                .HasForeignKey("FormCategoryId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.FormAggregate.Version", "VersionModified", b1 =>
                        {
                            b1.Property<int>("FormCategoryId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.HasKey("FormCategoryId");

                            b1.ToTable("FormCategory", "staging");

                            b1.WithOwner()
                                .HasForeignKey("FormCategoryId");
                        });

                    b.Navigation("VersionCreated");

                    b.Navigation("VersionDeleted");

                    b.Navigation("VersionModified");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormElement", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.FormAggregate.FormCategory", null)
                        .WithMany("Elements")
                        .HasForeignKey("FormCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Staging.Domain.AggregatesModel.FormAggregate.Version", "VersionCreated", b1 =>
                        {
                            b1.Property<int>("FormElementId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.HasKey("FormElementId");

                            b1.ToTable("FormElement", "staging");

                            b1.WithOwner()
                                .HasForeignKey("FormElementId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.FormAggregate.Version", "VersionDeleted", b1 =>
                        {
                            b1.Property<int>("FormElementId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.HasKey("FormElementId");

                            b1.ToTable("FormElement", "staging");

                            b1.WithOwner()
                                .HasForeignKey("FormElementId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.FormAggregate.Version", "VersionModified", b1 =>
                        {
                            b1.Property<int>("FormElementId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.HasKey("FormElementId");

                            b1.ToTable("FormElement", "staging");

                            b1.WithOwner()
                                .HasForeignKey("FormElementId");
                        });

                    b.Navigation("VersionCreated");

                    b.Navigation("VersionDeleted");

                    b.Navigation("VersionModified");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormElementAttribute", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.FormAggregate.FormElement", null)
                        .WithMany("Attributes")
                        .HasForeignKey("FormElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormElementDependency", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.FormAggregate.FormElement", null)
                        .WithMany("Dependencies")
                        .HasForeignKey("FormElementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormVersion", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.FormAggregate.Form", null)
                        .WithMany("Versions")
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Staging.Domain.AggregatesModel.FormAggregate.Version", "Version", b1 =>
                        {
                            b1.Property<int>("FormVersionId")
                                .HasColumnType("int");

                            b1.Property<int>("Major")
                                .HasColumnType("int");

                            b1.Property<int>("Minor")
                                .HasColumnType("int");

                            b1.HasKey("FormVersionId");

                            b1.ToTable("FormVersion", "staging");

                            b1.WithOwner()
                                .HasForeignKey("FormVersionId");
                        });

                    b.Navigation("Version");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.Package", b =>
                {
                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "PackageClosed", b1 =>
                        {
                            b1.Property<int>("PackageId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageId");

                            b1.ToTable("Package", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "PackageOpened", b1 =>
                        {
                            b1.Property<int>("PackageId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageId");

                            b1.ToTable("Package", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.Navigation("PackageClosed");

                    b.Navigation("PackageOpened");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.Package", null)
                        .WithMany("Events")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlag", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", null)
                        .WithMany("Flags")
                        .HasForeignKey("PackageEventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "FlagDeferred", b1 =>
                        {
                            b1.Property<int>("PackageEventDataFlagId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventDataFlagId");

                            b1.ToTable("PackageEventDataFlag", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventDataFlagId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "FlagResolved", b1 =>
                        {
                            b1.Property<int>("PackageEventDataFlagId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventDataFlagId");

                            b1.ToTable("PackageEventDataFlag", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventDataFlagId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.PersonIdentifier", "Requester", b1 =>
                        {
                            b1.Property<int>("PackageEventDataFlagId")
                                .HasColumnType("int");

                            b1.Property<string>("Email")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("FullName")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PackageEventDataFlagId");

                            b1.ToTable("PackageEventDataFlag", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventDataFlagId");
                        });

                    b.Navigation("FlagDeferred");

                    b.Navigation("FlagResolved");

                    b.Navigation("Requester");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlagComment", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlag", null)
                        .WithMany("Comments")
                        .HasForeignKey("PackageEventDataFlagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDevice", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", null)
                        .WithMany("Devices")
                        .HasForeignKey("PackageEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", null)
                        .WithMany("Households")
                        .HasForeignKey("PackageEventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "Accepted", b1 =>
                        {
                            b1.Property<int>("PackageEventHouseholdId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventHouseholdId");

                            b1.ToTable("PackageEventHousehold", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "Rejected", b1 =>
                        {
                            b1.Property<int>("PackageEventHouseholdId")
                                .HasColumnType("int");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventHouseholdId");

                            b1.ToTable("PackageEventHousehold", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdId");
                        });

                    b.Navigation("Accepted");

                    b.Navigation("Rejected");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdAttribute", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", null)
                        .WithMany("Attributes")
                        .HasForeignKey("PackageEventHouseholdId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.AttributeValue", "Modified", b1 =>
                        {
                            b1.Property<int>("PackageEventHouseholdAttributeId")
                                .HasColumnType("int");

                            b1.Property<string>("SelectionKey")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SelectionValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PackageEventHouseholdAttributeId");

                            b1.ToTable("PackageEventHouseholdAttribute", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdAttributeId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.AttributeValue", "Original", b1 =>
                        {
                            b1.Property<int>("PackageEventHouseholdAttributeId")
                                .HasColumnType("int");

                            b1.Property<string>("SelectionKey")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SelectionValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PackageEventHouseholdAttributeId");

                            b1.ToTable("PackageEventHouseholdAttribute", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdAttributeId");
                        });

                    b.Navigation("Modified");

                    b.Navigation("Original");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMember", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", null)
                        .WithMany("Members")
                        .HasForeignKey("PackageEventHouseholdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMemberAttribute", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMember", null)
                        .WithMany("Attributes")
                        .HasForeignKey("PackageEventHouseholdMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.AttributeValue", "Modified", b1 =>
                        {
                            b1.Property<int>("PackageEventHouseholdMemberAttributeId")
                                .HasColumnType("int");

                            b1.Property<string>("SelectionKey")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SelectionValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PackageEventHouseholdMemberAttributeId");

                            b1.ToTable("PackageEventHouseholdMemberAttribute", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdMemberAttributeId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.AttributeValue", "Original", b1 =>
                        {
                            b1.Property<int>("PackageEventHouseholdMemberAttributeId")
                                .HasColumnType("int");

                            b1.Property<string>("SelectionKey")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SelectionValue")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("Value")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PackageEventHouseholdMemberAttributeId");

                            b1.ToTable("PackageEventHouseholdMemberAttribute", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdMemberAttributeId");
                        });

                    b.Navigation("Modified");

                    b.Navigation("Original");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynch", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", null)
                        .WithMany("Synchs")
                        .HasForeignKey("PackageEventHouseholdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynchMetaAttribute", b =>
                {
                    b.HasOne("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynch", null)
                        .WithMany("MetaAttributes")
                        .HasForeignKey("PackageEventHouseholdSynchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.Form", b =>
                {
                    b.Navigation("Categories");

                    b.Navigation("Versions");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormCategory", b =>
                {
                    b.Navigation("Elements");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.FormAggregate.FormElement", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.Package", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Flags");

                    b.Navigation("Households");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlag", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Members");

                    b.Navigation("Synchs");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMember", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynch", b =>
                {
                    b.Navigation("MetaAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
