// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Staging.Infrastructure;

#nullable disable

namespace Staging.Infrastructure.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    partial class DatabaseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("staging")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.Package", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("PackageTypeId")
                        .HasColumnType("int");

                    b.Property<bool>("System")
                        .HasColumnType("bit");

                    b.Property<string>("UniqueCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("UniqueCode")
                        .IsUnique();

                    b.ToTable("Package", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("OrgUnitId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PackageId");

                    b.ToTable("PackageEvent", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("DataFlagTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("HouseholdMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("SystemGenerated")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventId");

                    b.ToTable("PackageEventDataFlag", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlagComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("OriginatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageEventDataFlagId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventDataFlagId");

                    b.ToTable("PackageEventDataFlagComment", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("EnumeratorName")
                        .HasMaxLength(75)
                        .HasColumnType("nvarchar(75)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageEventId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventId");

                    b.ToTable("PackageEventDevice", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ContactNumber")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HouseholdHead")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("HouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageEventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Village")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventId");

                    b.ToTable("PackageEventHousehold", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageEventHouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ValueModified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdId");

                    b.ToTable("PackageEventHouseholdAttribute", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IDDocumentType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("IdentificationNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageEventHouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdId");

                    b.ToTable("PackageEventHouseholdMember", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMemberAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttributeKey")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageEventHouseholdMemberId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("ValueModified")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdMemberId");

                    b.ToTable("PackageEventHouseholdMemberAttribute", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PackageEventHouseholdId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Payload")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdId");

                    b.ToTable("PackageEventHouseholdSynch", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynchMetaAttribute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Created")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("CreatedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LastModifiedId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("MetaAttributeTypeId")
                        .HasColumnType("int");

                    b.Property<string>("MetaAttributeValue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PackageEventHouseholdSynchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PackageEventHouseholdSynchId");

                    b.ToTable("PackageEventHouseholdSynchMetaAttribute", "staging");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.Package", b =>
                {
                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "PackageClosed", b1 =>
                        {
                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageId");

                            b1.ToTable("Package", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "PackageOpened", b1 =>
                        {
                            b1.Property<Guid>("PackageId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageId");

                            b1.ToTable("Package", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageId");
                        });

                    b.Navigation("PackageClosed");

                    b.Navigation("PackageOpened");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.Package", null)
                        .WithMany("Events")
                        .HasForeignKey("PackageId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "DataAcceptanceStageClosed", b1 =>
                        {
                            b1.Property<Guid>("PackageEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventId");

                            b1.ToTable("PackageEvent", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "DataManagementStageClosed", b1 =>
                        {
                            b1.Property<Guid>("PackageEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventId");

                            b1.ToTable("PackageEvent", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "DeviceRegisteredStageClosed", b1 =>
                        {
                            b1.Property<Guid>("PackageEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventId");

                            b1.ToTable("PackageEvent", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "EventOpened", b1 =>
                        {
                            b1.Property<Guid>("PackageEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventId");

                            b1.ToTable("PackageEvent", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "GatewayStageClosed", b1 =>
                        {
                            b1.Property<Guid>("PackageEventId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventId");

                            b1.ToTable("PackageEvent", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventId");
                        });

                    b.Navigation("DataAcceptanceStageClosed");

                    b.Navigation("DataManagementStageClosed");

                    b.Navigation("DeviceRegisteredStageClosed");

                    b.Navigation("EventOpened");

                    b.Navigation("GatewayStageClosed");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlag", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", null)
                        .WithMany("Flags")
                        .HasForeignKey("PackageEventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "FlagDeferred", b1 =>
                        {
                            b1.Property<Guid>("PackageEventDataFlagId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventDataFlagId");

                            b1.ToTable("PackageEventDataFlag", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventDataFlagId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "FlagResolved", b1 =>
                        {
                            b1.Property<Guid>("PackageEventDataFlagId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventDataFlagId");

                            b1.ToTable("PackageEventDataFlag", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventDataFlagId");
                        });

                    b.Navigation("FlagDeferred");

                    b.Navigation("FlagResolved");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlagComment", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlag", null)
                        .WithMany("Comments")
                        .HasForeignKey("PackageEventDataFlagId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDevice", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", null)
                        .WithMany("Devices")
                        .HasForeignKey("PackageEventId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", null)
                        .WithMany("Households")
                        .HasForeignKey("PackageEventId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "Accepted", b1 =>
                        {
                            b1.Property<Guid>("PackageEventHouseholdId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventHouseholdId");

                            b1.ToTable("PackageEventHousehold", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "Enumerated", b1 =>
                        {
                            b1.Property<Guid>("PackageEventHouseholdId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventHouseholdId");

                            b1.ToTable("PackageEventHousehold", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.StatusChange", "Rejected", b1 =>
                        {
                            b1.Property<Guid>("PackageEventHouseholdId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime?>("ChangeDate")
                                .HasColumnType("datetime2");

                            b1.Property<bool>("Status")
                                .HasColumnType("bit");

                            b1.HasKey("PackageEventHouseholdId");

                            b1.ToTable("PackageEventHousehold", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdId");
                        });

                    b.Navigation("Accepted");

                    b.Navigation("Enumerated");

                    b.Navigation("Rejected");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdAttribute", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", null)
                        .WithMany("Attributes")
                        .HasForeignKey("PackageEventHouseholdId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.AttributeValue", "Modified", b1 =>
                        {
                            b1.Property<Guid>("PackageEventHouseholdAttributeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SelectionKey")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SelectionValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PackageEventHouseholdAttributeId");

                            b1.ToTable("PackageEventHouseholdAttribute", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdAttributeId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.AttributeValue", "Original", b1 =>
                        {
                            b1.Property<Guid>("PackageEventHouseholdAttributeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SelectionKey")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SelectionValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PackageEventHouseholdAttributeId");

                            b1.ToTable("PackageEventHouseholdAttribute", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdAttributeId");
                        });

                    b.Navigation("Modified");

                    b.Navigation("Original");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMember", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", null)
                        .WithMany("Members")
                        .HasForeignKey("PackageEventHouseholdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMemberAttribute", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMember", null)
                        .WithMany("Attributes")
                        .HasForeignKey("PackageEventHouseholdMemberId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.AttributeValue", "Modified", b1 =>
                        {
                            b1.Property<Guid>("PackageEventHouseholdMemberAttributeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SelectionKey")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SelectionValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PackageEventHouseholdMemberAttributeId");

                            b1.ToTable("PackageEventHouseholdMemberAttribute", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdMemberAttributeId");
                        });

                    b.OwnsOne("Staging.Domain.AggregatesModel.PackageAggregate.AttributeValue", "Original", b1 =>
                        {
                            b1.Property<Guid>("PackageEventHouseholdMemberAttributeId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("SelectionKey")
                                .HasColumnType("nvarchar(max)");

                            b1.Property<string>("SelectionValue")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("PackageEventHouseholdMemberAttributeId");

                            b1.ToTable("PackageEventHouseholdMemberAttribute", "staging");

                            b1.WithOwner()
                                .HasForeignKey("PackageEventHouseholdMemberAttributeId");
                        });

                    b.Navigation("Modified");

                    b.Navigation("Original");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynch", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", null)
                        .WithMany("Synchs")
                        .HasForeignKey("PackageEventHouseholdId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynchMetaAttribute", b =>
                {
                    b.HasOne("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynch", null)
                        .WithMany("MetaAttributes")
                        .HasForeignKey("PackageEventHouseholdSynchId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.Package", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEvent", b =>
                {
                    b.Navigation("Devices");

                    b.Navigation("Flags");

                    b.Navigation("Households");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventDataFlag", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHousehold", b =>
                {
                    b.Navigation("Attributes");

                    b.Navigation("Members");

                    b.Navigation("Synchs");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdMember", b =>
                {
                    b.Navigation("Attributes");
                });

            modelBuilder.Entity("MISSA.Services.Staging.Domain.AggregatesModel.PackageAggregate.PackageEventHouseholdSynch", b =>
                {
                    b.Navigation("MetaAttributes");
                });
#pragma warning restore 612, 618
        }
    }
}
